# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Stepping In IT 
tagline:          'When IT feels like mucking barnstalls'
description:      'A brazen two-column blog that pairs a prominent sarcasm with uncomplicated contempt. Theme by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://www.uberkinder.com
baseurl:          /

author:
  name:           'Daniel Schmeltz'
  url:            https://www.uberkinder.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/uberkind9
